### ISSUE TITLE
I  can't open choose ,please help me 

### ISSUE THREAD

**Issue by oushiei120** [daeh/zotero-markdb-connect#118] opened 2024-05-20 02:57 UTC
<img width="490" alt="image" src="https://github.com/daeh/zotero-markdb-connect/assets/86762134/92cdf0e3-d018-4d47-9450-e993a6d9aa50">
It don't work well in mac m1

https://github.com/daeh/zotero-markdb-connect/assets/86762134/ef6e4a65-cb63-49a7-a5a4-006c7e788c50

**Comment by Litt7e** [comment] 2024-05-20 03:44
I have the same problem.

**Comment by daeh** [comment] 2024-05-20 05:06
Pretty hard to help without more info, since it works fine on my system (which is also a silicon Mac). It's usually a good idea to include details like the version of Zotero, version of the plugin, etc. For troubleshooting, I highly recommend looking at the error console to see if anything is being reported when you click the button (`Tools > Developer > Error Console`).

**Comment by oushiei120** [comment] 2024-05-20 14:54
I'm sorry, I have no idea what this means

**Comment by daeh** [comment] 2024-05-20 16:32
What version of Zotero and MDBC are you using?

@Litt7e what language localization are you using? Is it also Chinese?

One trouble shooting step would be to switch Zotero's language to english and see if that changes anything. (I don't know why it would, but if it does, that will be very informative.)

**Comment by daeh** [comment] 2024-05-20 16:41
FYI, if you want to set the path manually, you can by going to `File > Settings... > Advanced > Config Editor`

and setting the value of `extensions.mdbconnect.source_dir` to the directory (e.g. `/Users/me/Documents/ObsidianVault/MyReadingNotes`)

![CleanShot 2024-05-20 at 12 36 55@2x](https://github.com/daeh/zotero-markdb-connect/assets/12652166/42030a0a-06f2-4f86-a44b-8a5c9bde176f)

**Comment by Litt7e** [comment] 2024-05-21 07:24
> What version of Zotero and MDBC are you using?
> 
> @Litt7e what language localization are you using? Is it also Chinese?
> 
> One trouble shooting step would be to switch Zotero's language to english and see if that changes anything. (I don't know why it would, but if it does, that will be very informative.)

Yes，I‘m Chinese. I do as you say switch Zotero's language to English, but still nothing happen when I click the "Choose" button.
And here is the Error console:
![image](https://github.com/daeh/zotero-markdb-connect/assets/44261353/5ec96426-969d-4d20-9181-adb8434ad64c)

**Comment by daeh** [comment] 2024-05-21 13:53
please give me the version numbers of Zotero and MDBC

**Comment by daeh** [comment] 2024-05-21 17:40
So to reiterate, I can't reproduce this issue. But here are some more trouble shooting ideas to help us narrow down where the issue is.

See if this code opens the dialog box. You can run it by going to `Tools > Developer > Run JavaScript`.

```javascript
Zotero.MDBC.hooks.onPrefsEvent('chooseVaultFolder')
```

<img width="910" alt="Screenshot 2024-05-21 at 13 28 46" src="https://github.com/daeh/zotero-markdb-connect/assets/12652166/52a5eb2e-4d5a-4038-9b59-94ef0cb39270">


If it throws an error about `Object`, try running just `Zotero.MDBC.hooks` and make sure it returns something like 

```javascript
{
    "onStartup": async function ba(){...}
    "onShutdown": function Ca(){...}
    "onMainWindowLoad": async function gr(a){...}
    "onMainWindowUnload": async function Ia(a){...}
    "onPrefsEvent": async function $a(a,e){...}
    "syncMarkDB": function ya(){...}
    "syncMarkDBReport": function va(){...}
    "syncMarkDBSaveDebug": function fr(){...}
    "Logs": function Ra(){...}
    "DataStore": function _a(){...}
    "Data": function xa(){...}
    "DataZotIds": function Ta(){...}
    "saveLogs": function wa(){...}
    "saveJsonFile": function ka(a,e,t){...}
}
```

And you can also try

```javascript
Zotero.MDBC.hooks.saveLogs()
```

which should also open a File Picker dialog.

**Comment by Litt7e** [comment] 2024-05-22 01:46
zetero:7.0.0-beta.79+95d5a5417;
MDBC:0.1.0-rc.7;
Nothing happen after running Zotero.MDBC.hooks.saveLogs().
But I found out that in MDBC:0.1.0 the choose button can work properly.
![image](https://github.com/daeh/zotero-markdb-connect/assets/44261353/1adf2c99-3a62-412f-a6d5-48b8e26d2b27)
![image](https://github.com/daeh/zotero-markdb-connect/assets/44261353/44a038ca-e422-4a85-a613-61d8379f9026)
![image](https://github.com/daeh/zotero-markdb-connect/assets/44261353/19b3312d-47d6-4110-b7f2-b1b92baccb2d)

**Comment by daeh** [comment] 2024-05-22 02:55
ok, so am I understanding correctly that once you upgraded to MDBC v0.1.0 https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0 , everything started working correctly (namely the "Choose" button for picking the directory that your reading notes are stored in)?

@oushiei120 please make sure you're using the latest release ↑

**Comment by Litt7e** [comment] 2024-05-22 03:01
> ok, so am I understanding correctly that once you upgraded to MDBC v0.1.0 https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0 , everything started working correctly (namely the "Choose" button for picking the directory that your reading notes are stored in)?

Yes, your understanding is correct

**Comment by daeh** [comment] 2024-05-27 02:19
@oushiei120 I'm going assume that upgrading MDBC to v0.1.0 fixed this for you and close the issue, but please reopen it if you're still having problems.

**Closed by daeh** 2024-05-27 02:19 UTC
