### ISSUE TITLE
notes list incomplete in context menu

### ISSUE THREAD

**Issue by osaze-nosaze** [daeh/zotero-markdb-connect#19] opened 2022-04-14 23:04 UTC
Hi there!
Thanks for this plugin. I find, however, that when I right-click in Zotero on an Obsidian-Zotero synced item and point to "Open ObsidianMD Note" or "Show Markdown File" I only get a list that seems limited to 16 Obsidian notes although I may have many more notes with the relevant Zotero itemkey. I cannot seem to find any button to scroll down to see other notes or some other means to see them.
Is this perhaps by design, or is it a bug? Or am I doing something wrong?

I could not find any thread on this issue and decided to submit it as a new one. I am sorry if I missed an already-existing thread on it.
Thanks for your help

**Comment by daeh** [comment] 2022-04-15 14:52
That's the intended behavior. The workflow that inspired this plugin assumes there is only 1 MD note per Zotero Item. I relaxed that restriction to allow multiple notes per item, in case people had notes in different folders, or didn't realize that they had multiple notes. But number is capped at something like 16. Having that many MD notes for a single Zotero item is a different use case than the ones I've had in mind (plus, a contextual menu isn't a great place to have a super long list).

If you think yours might be a common use case, feel free to open an enhancement request and describe it.

**Comment by daeh** [comment] 2022-04-15 14:56
More specifically, it sounds like you're using the plugin to find every MD files where a zotero item is referenced, which is a different use case. This plugin is designed around the idea that there's one MD files where you take notes on a given Zotero item. Other notes then link to that main note, not the Zotero item itself, and to find those notes you'd use the Obsidian backlink function.

**Comment by osaze-nosaze** [comment] 2022-04-15 19:14
Hi, dae
Thanks for your explanations. I cannot say whether mine is a common use case, as it is possible I am using the plugin how it is not meant to be or expecting it to function how it is not meant to. The reason, I am sure, that multiple notes show up on the contextual menu is that I practice the smart note zettelkasten method (or am trying to). Yes, I have a hub note for each source but do not put all my study notes in it. Instead, it contains some basic bibliographical data about the source and links to the individual study notes I make from or about it. It serves, therefore, as, well, a hub for all those study notes, providing one search location--among others--when I am gathering my notes for analysis and writing on a subject. I have in each of those notes as  well as in the hub note a dataview field with the Zotero itemkey of the source, which links all the study notes, hub note, and Zotero source together. I suppose that is why all those detail notes, not only the hub note, show up in the plugin's contextual menu.
This is probably not the plugin's intended functioning but I have found the links in the contextual menu to those detail notes very useful in exploring my notes on any subject by jumping between Obsidian and Zotero. I have committed to the former as my note management application, the latter serving primarily as my reference manager. However, I have used Zotero for more than a decade and have thousands of notes there. It is easier now with Zotero 6 to convert notes to markdown and use them in Obsidian. However, the need to add links, tags, and other features to enhance their discoverability in Obsidian has made this a slow process--I am speaking of processing thousands of notes. Further complicating the process is that I have to split and refactor most of them because they tend to combine multiple ideas in one note, as I only recently started using the atomic notes method. So I still do much note reading in Zotero and often have to jump between it and Obsidian to explore related ideas in two or more notes, some on the former and others the latter. I was thrilled when I found that your plugin eased this back and forth. It is a pity that it only allows 16 notes.
You are correct that the contextual menu might not be the best place in which to present the links to a large number of Obsidian note. Lacking any knowledge of coding or programming, I cannot offer any intelligent suggestion on that. However, you might play around with the question and see what possibilities emerge.
Anyway, thanks for the plugin. It is very innovative and of immense practical value.

**Comment by daeh** [comment] 2023-12-09 23:28
Hi @osaze-nosaze I added more flexible contextual menu building to the zotero 7 compatible version of this plugin, which should resolve this issue. 

Having multiple markdown notes per zotero item still isn't the intended use case, but there shouldn't be anything preventing you from using a custom RegEx to list every markdown file with a BetterBibTeX citekey or Zotero Item Id in contextual menu of Zotero items

Any version >= than `0.1.0-rc.1` should work

https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0-rc.1

**Comment by daeh** [comment] 2024-03-29 01:47
Closing as resolved. @osaze-nosaze feel free to reopen if `v0.1.0` or later doesn't work for you.

**Closed by daeh** 2024-03-29 01:47 UTC
Labels: enhancement

**Comment by fornewfork** [comment] 2025-06-07 16:38
For "Zotero-Item-Key - captured with custom RegExp", if the same markdown note contains two Zotero Item Keys, only the first one will be matched. 

**User Case： I describe a series of paper in the same Obsidian note, which correspond to the same theme, so multiple Zotero links will be included in the same note. **

For example, the note "test.md" with following content and regex `\[💤.*\]\(zotero:.*items\/([a-zA-Z0-9]{8})\)`

```
- [💤A](zotero://select/library/items/DFIV6M5K)
- [💤B](zotero://select/library/items/PS23VBTJ)
```
Only the first term "DFIV6M5K" will be match in Zotero. And you could check it by change order of  the content as follow.

```
- [💤B](zotero://select/library/items/PS23VBTJ)
- [💤A](zotero://select/library/items/DFIV6M5K)
```

Please check it. Thanks for your work!

**Comment by daeh** [comment] 2025-06-07 20:24
> For "Zotero-Item-Key - captured with custom RegExp", if the same markdown note contains two Zotero Item Keys, only the first one will be matched.

If I'm understanding correctly, this is the intended behavior, see the README, e.g.

> NOTE: multiple markdown files can point to the same Zotero item. But a given markdown file should only be linked to a single Zotero item. A markdown reading note can reference multiple Zotero items throughout the file, but MarkDB-Connect will only link the markdown note to one BetterBibTeX-citekey / Zotero-Item-Key.
